### ISSUE TITLE
s.youtube.com being blocked via the adaway blocklist

### ISSUE THREAD

**Issue by Glenta** [mullvad/dns-adblock#10]
When trying to watch YouTube and having adblock on, Watch History is not being updated since the domain s.youtube.com is being blocked. If you check the adaway blocklist you can see that s.youtube.com is there. [Here](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212) is a source for other domains needed for web functionality as well.

**Comment by jbjorkang** [comment]
Thanks for your issue!

If it is Adaway that are blocking it it would probably be better to contact them directly by whichever means they have.

If they do remove this, or if there's a reason for them not to, I'll gladly consider making an exception for it.

**Comment by Glenta** [comment]
> 
> 
> Thanks for your issue!
> 
> If it is Adaway that are blocking it it would probably be better to contact them directly by whichever means they have.
> 
> If they do remove this, or if there's a reason for them not to, I'll gladly consider making an exception for it.

Seems two people already have already reported this issue but nothing has happened in 10 days [this issue](https://github.com/AdAway/AdAway/issues/2890) being the oldest. I'll try reporting again and hope someone sees.

**Comment by Glenta** [comment]
After more than two weeks, an AdAway maintainer or someone with at least some authority has not seen/acknowledged this issue. And it would be great if I can block ads and watch YouTube at the same time.

**Comment by jbjorkang** [comment]
Since we rely on a number of other block lists, and we aren't currently looking at maintaining any alterations, we will have to stick with what we have for now.

If it gets resolved via Adaway, then we will integrate those updates in future.
