### ISSUE TITLE
Possibility to add additional blocklists?

### ISSUE THREAD

**Issue by RooneyMcNibNug** [mullvad/dns-adblock#11]
Hello, 

Thanks for the good VPN service - they are rare these days. 😄 

I am wondering if there is a vetting process or anything for adding additional blocklists to this functionality.

I have a domain-based blocklist that I have been working on over the years myself that might be worth adding, for example: 
https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt

This is a list that I use myself - for personal and work networks - so I can vouch that when something breaks I am eager to fix it pretty fast.

Is there a more rigid process I can go through for this? Or is your team not really looking to add additional blocklists at the moment?

Cheers,
-Rooney

**Comment by jbjorkang** [comment]
Hey,

Thanks for your issue. For now we are sticking with the lists we have, but that might well change in the future! 

Thanks a lot for your contribution though, really nice to see the community wanting to contribute!

Joshua
