### ISSUE TITLE
Configuration for WireGuard

### ISSUE THREAD

**Issue by speg** [mullvad/dns-adblock#13]
Hi!

mullvad (and WireGuard) newbie. 

Is it possible to use this feature when using WireGuard for iOS?

I see a `DNS Servers 193.138.218.74` setting after I loaded the mullvad config file. 

Would it be as simple as changing that to an adblocking address?

**Comment by oskaralmlov** [comment]
Hi,

You should be able to replace the DNS-server in your configuration with one of the IPs listed in this blog post:

https://mullvad.net/sv/blog/2021/5/27/how-set-ad-blocking-our-app/

Have a nice weekend and happy ad-blocking :)

**Comment by jbjorkang** [comment]
I'll close this issue as resolved! 💯
