### ISSUE TITLE
Add some tracker into custom

### ISSUE THREAD

**Issue by BirdInFire** [mullvad/dns-adblock#21]
# I actually have (thanks to apple news system found 3 tracker not blocked and two i'm not sure it must be blocked (even if they can be used as tracker)):

### Adobe analytics
- assets.adobedtm.com 

### Microsoft analytics
- in.appcenter.ms 

### Firebase unique identifier : Sources : https://firebase.google.com/docs/reference/android/com/google/firebase/installations/FirebaseInstallations
- firebaseinstallations.googleapis.com 

### Can be user as tracker but have more usefull feature : Sources : https://firebase.google.com/docs/remote-config/
- firebaseremoteconfig.googleapis.com 

### Apple Statistics
- cstat.apple.com

# Note : I have made this report only to present eventual thread i will understand if for any reason these are not added.

**Comment by oskaralmlov** [comment]
Hello and thanks for your input!

We are currently rethinking how we work with DNS adblocking and we'll do some changes in the near future. We won't be adding these domains to our current lists but we'll keep your proposals in mind for when we work on  future changes.
