### ISSUE TITLE
Malware block list not shown

### ISSUE THREAD

**Issue by jjpinom** [mullvad/dns-adblock#24]
Hello!.

Today I'm testing the 2022.1 Beta 1 version for windows.

Mullvad is including malware blocking, but the blocking list is not shown here, I didn't find any detail on the malware blocking list on the blog.

Thanks in advance!

**Comment by jbjorkang** [comment]
Thanks for your feedback. We will have a blog post detailing what we do coming soon.

Until that is out, this is the TL;DR url​ we use (for now, certainly subject to additions in future): ​https://urlhaus.abuse.ch/downloads/rpz/

**Comment by BirdInFire** [comment]
@jbjorkang when whe use manual config (openvpn or wireguard) does the dns with malware remain the same : 100.64.0.3 or is it a new one ? like : 100.64.0.4 ???

Thanks

**Comment by jbjorkang** [comment]
> @jbjorkang when whe use manual config (openvpn or wireguard) does the dns with malware remain the same : 100.64.0.3 or is it a new one ? like : 100.64.0.4 ???
> 
> Thanks

It will be this:

 100.64.0.1 - Ad blocking only
 100.64.0.2 - Trackers only
 100.64.0.3 - Ad blocking, trackers, no malware blocking
 100.64.0.4 - Malware blocking only
 100.64.0.5 - Ad blocking, malware blocking, no tracker blocking
 100.64.0.6 - Tracker, malware blocking, no ad blocking
 100.64.0.7 - Ad blocking, tracker and malware blocking (“everything”)

Blog soon, this is also on our FAQ: https://mullvad.net/en/help/search/?q=dns#74

**Comment by jbjorkang** [comment]
> Thanks ;)

You are most welcome!
