### ISSUE TITLE
chtbl.com being blocked despite being removed from blocklist

### ISSUE THREAD

**Issue by frank-owen** [mullvad/dns-adblock#34]
The domain chtbl.com appears to still be being blocked using doh on android. This breaks some podcasts.

The domain was removed from the custom list here e8c63360836ca384bd888cb29e1f68cf70f9fb55 and was removed from adaway a year ago https://github.com/AdAway/adaway.github.io/commit/b6665b8d0dcb44e1ed71ae767b71dca0dd72863b It doesn't appear in the output.txt however it still resolves to 0.0.0.0. The domain resolves correctly when changing to a different dns.

**Comment by jbjorkang** [comment]
Thanks for this, I'll ensure this gets updated on our DoH servers.

**Comment by xanoni** [comment]
Came here to report the same. Can confirm that this is still an issue. Goes straight to localhost.

**Comment by xanoni** [comment]
Thank you.

1) Did anyone  check what Chtbl actually does? Seems it's "Google Analytics for Podcasts"? Tracks how many people listen to each episode, where they are from, etc.? Probably also stores IP addresses and client info, so knows all the things in my queue and played list? If yes, then not great that podcasters choose to use this. But this is the world we live in ...

2) Did anyone check which services it affects / doesn't affect? Maybe worth getting certain podcasts via alternative sources like RSS feeds or so.

3) A bit off topic: is it possible to choose a Mullvad DNS server that's geographically different from the VPN exit location? By default it automatically picks the closest server. (But strangely sometimes I noticed it picked a DNS server in London even when the WG exit was in North America). Would be nice if we could add some ambiguity here and there.

**Comment by jbjorkang** [comment]
This has been rolled out to all of the DoH servers

**Comment by frank-owen** [comment]
Confirmed fixed, thanks.
