### ISSUE TITLE
Add Spotify

### ISSUE THREAD

**Issue by account123123123** [mullvad/dns-adblock#39]
not sure if this is a comprehensive list. spotify would be helpful

edit: https://gist.github.com/opus-x/3e673a9d5db2a214df05929a4eee6a57#file-spotify_eliminate_advertisements

**Comment by jbjorkang** [comment]
Thanks. How did you obtain this list?

**Comment by jbjorkang** [comment]
Thanks for these lists. For now we will close this issue, but we will keep this in mind for future updates
