### ISSUE TITLE
Ad & User tracking domains in iOS apps 

### ISSUE THREAD

**Issue by ciukas1** [mullvad/dns-adblock#4]
Hello,

Can the following Ad tracking/user tracking domains be added to the block list for the following apps on iOS?

Kindle/Comixology/Manga:
device-metrics-us.amazon.com
amazon-adsystem.com
adcolony.com
adtilt.com
app-measurement.com
crashlytics.com
imanga.nyc3.digitaloceanspaces.com
imanga.oss-cn-qingdao.aliyuncs.com
trafficmanager.net

Nytimes:
platform.twitter.com

Others/Misc:
stun.l.google.com
ad.daum.net
revenuecat.com
graphql.instagram.com
graph.facebook.com
www.paypalobjects.com
braze.com
unity3d.com
stats.nba.com
cdn.calculator-tech.com

Edit 17/06:
graph.facebook.com
edge-mqtt.facebook.com
portal.fb.com

**Comment by jbjorkang** [comment]
Thanks for your feedback on our lists. We will keep them in mind for future updates!
