### ISSUE TITLE
add more filter options via DoH

### ISSUE THREAD

**Issue by slymax** [mullvad/dns-adblock#40]
as I understand it, `adblock.doh.mullvad.net` is currently the only filter option available via DoH. I assume that it uses the same filters as `100.64.0.1`?

It would be cool if the other filter options could be made available via DoH as well. I'd be particularly interested in what `100.64.0.7` does.

**Comment by jbjorkang** [comment]
Thanks for this, it is going to be the case that we upgrade our DoH servers in the future. We will ever likely add different lists at the same time. I cannot say exactly when this will happen, however.

For this, yes, DoH uses the same list as `100.64.0.1`
