### ISSUE TITLE
Add non-English easylist lists

### ISSUE THREAD

**Issue by cd4d** [mullvad/dns-adblock#42]
Easylist has other lists for  [non-English websites](https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html)

_Every supplement removes unwanted items from a particular genre of websites that are not specifically or completely dealt with by the primary EasyList, and might increase the blocking efficiency of the ad blocker used for people who regularly visit non-English domains._

Since Mullvad provides services with servers on multiple continents, having its ad-blocking feature working on non-English website makes a lot of sense.

**Comment by jbjorkang** [comment]
Thanks for this, we will consider such lists for future updates

**Comment by jbjorkang** [comment]
I will close this for the time being. We would like to add more lists, if you have any suggestions of lists that follow our required format (which you can see in our codebase) we would be greatly appreciative.
