### ISSUE TITLE
DoH DoT mobileconfig profiles for iOS

### ISSUE THREAD

**Issue by Eow2022yia** [mullvad/dns-adblock#55]
Hi,

I am aware this has been posted previously by another user but to show my strong support for this feature I am mentioning this again.

Please strongly consider creating .mobileconfig files for easy access for iPhone/iPad/Mac users to your wonderful Ad-block DNS resolver?

Thank you.

**Comment by jbjorkang** [comment]
We have not got anything to share right now, but this is a good idea that would certainly help our userbase. Thanks for your feedback, we will keep it in mind for future updates.

**Comment by marcoclg19** [comment]
> We have not got anything to share right now, but this is a good idea that would certainly help our userbase. Thanks for your feedback, we will keep it in mind for future updates.

Hi, any news? :)

**Comment by jbjorkang** [comment]
> > We have not got anything to share right now, but this is a good idea that would certainly help our userbase. Thanks for your feedback, we will keep it in mind for future updates.
> 
> Hi, any news? :)

Nothing to share currently, but I am keen myself to have something like this on many platforms. It would be very convenient to avoid multiple click configurations.
